// Registry of every public source the app relays. Add here first; refer by id
// everywhere else so a citation is always spelled the same way.
import type { SourceRef } from "./types";

export const SOURCES = {
  "bls-oews": { id: "bls-oews", name: "Occupational Employment and Wage Statistics", publisher: "U.S. Bureau of Labor Statistics", url: "https://www.bls.gov/oes/", license: "public domain" },
  "bls-qcew": { id: "bls-qcew", name: "Quarterly Census of Employment and Wages", publisher: "U.S. Bureau of Labor Statistics", url: "https://www.bls.gov/cew/", license: "public domain" },
  "zillow-zhvi": { id: "zillow-zhvi", name: "Zillow Home Value Index (ZHVI)", publisher: "Zillow Research", url: "https://www.zillow.com/research/data/", license: "free for public use with attribution" },
  "zillow-zori": { id: "zillow-zori", name: "Zillow Observed Rent Index (ZORI)", publisher: "Zillow Research", url: "https://www.zillow.com/research/data/", license: "free for public use with attribution" },
  fred: { id: "fred", name: "FRED Economic Data", publisher: "Federal Reserve Bank of St. Louis", url: "https://fred.stlouisfed.org/", license: "FRED terms; series from their original publishers" },
  "bts-border": { id: "bts-border", name: "Border Crossing Entry Data", publisher: "U.S. Bureau of Transportation Statistics", url: "https://data.bts.gov/", license: "public domain" },
  "bts-ports": { id: "bts-ports", name: "Port Performance Freight Statistics", publisher: "U.S. Bureau of Transportation Statistics", url: "https://data.bts.gov/", license: "public domain" },
  "bts-supply-chain": { id: "bts-supply-chain", name: "Supply Chain and Freight Indicators", publisher: "U.S. Bureau of Transportation Statistics", url: "https://data.bts.gov/", license: "public domain" },
  "nga-wpi": { id: "nga-wpi", name: "World Port Index (Pub 150)", publisher: "National Geospatial-Intelligence Agency", url: "https://msi.nga.mil/Publications/WPI", license: "public domain" },
  "worldbank-wdi": { id: "worldbank-wdi", name: "World Development Indicators", publisher: "World Bank", url: "https://data.worldbank.org/", license: "CC BY 4.0" },
  "worldbank-wits": { id: "worldbank-wits", name: "WITS TradeStats", publisher: "World Bank", url: "https://wits.worldbank.org/", license: "CC BY 4.0" },
  "census-tigerweb": { id: "census-tigerweb", name: "TIGERweb", publisher: "U.S. Census Bureau", url: "https://tigerweb.geo.census.gov/", license: "public domain" },
  "usgs-water": { id: "usgs-water", name: "USGS Water Data API", publisher: "U.S. Geological Survey", url: "https://api.waterdata.usgs.gov/", license: "public domain" },
  "usgs-stat": { id: "usgs-stat", name: "USGS Water Data Statistics API (daily streamflow percentiles)", publisher: "U.S. Geological Survey", url: "https://api.waterdata.usgs.gov/statistics/v0/", license: "public domain" },
  "noaa-nwps": { id: "noaa-nwps", name: "National Water Prediction Service", publisher: "NOAA National Weather Service", url: "https://api.water.noaa.gov/", license: "public domain" },
  twdb: { id: "twdb", name: "Water Data for Texas reservoirs", publisher: "Texas Water Development Board", url: "https://www.waterdatafortexas.org/reservoirs", license: "public" },
  usdm: { id: "usdm", name: "U.S. Drought Monitor", publisher: "National Drought Mitigation Center, USDA, NOAA", url: "https://droughtmonitor.unl.edu/", license: "public with attribution" },
  "usgs-earthquakes": { id: "usgs-earthquakes", name: "Earthquake Hazards Program feeds", publisher: "U.S. Geological Survey", url: "https://earthquake.usgs.gov/", license: "public domain" },
  "adsb-lol": { id: "adsb-lol", name: "adsb.lol ADS-B feed", publisher: "adsb.lol", url: "https://adsb.lol/", license: "ODbL" },
  opensky: { id: "opensky", name: "OpenSky Network", publisher: "OpenSky Network", url: "https://opensky-network.org/", license: "OpenSky terms (non-commercial)" },
  digitraffic: { id: "digitraffic", name: "Marine traffic AIS", publisher: "Fintraffic / Digitraffic", url: "https://www.digitraffic.fi/en/marine-traffic/", license: "CC BY 4.0" },
  aisstream: { id: "aisstream", name: "AISStream", publisher: "AISStream.io", url: "https://aisstream.io/", license: "free key; AISStream terms" },
  celestrak: { id: "celestrak", name: "GP element sets", publisher: "CelesTrak", url: "https://celestrak.org/", license: "CelesTrak terms" },
  "sec-edgar": { id: "sec-edgar", name: "EDGAR company filings and XBRL APIs", publisher: "U.S. Securities and Exchange Commission", url: "https://www.sec.gov/search-filings/edgar-application-programming-interfaces", license: "public domain; fair-access policy (10 req/s, User-Agent)" },
  "fdic-bankfind": { id: "fdic-bankfind", name: "BankFind Suite API", publisher: "Federal Deposit Insurance Corporation", url: "https://banks.data.fdic.gov/docs/", license: "public domain" },
  usaspending: { id: "usaspending", name: "USAspending API", publisher: "U.S. Department of the Treasury", url: "https://api.usaspending.gov/", license: "public domain" },
  "census-zcta-county": { id: "census-zcta-county", name: "ZCTA to county relationship file (2020)", publisher: "U.S. Census Bureau", url: "https://www.census.gov/geographies/reference-files/time-series/geo/relationship-files.html", license: "public domain" },
  "sentinel-2": { id: "sentinel-2", name: "Copernicus Sentinel-2 L2A", publisher: "ESA via Element 84 Earth Search", url: "https://earth-search.aws.element84.com/v1", license: "free and open (Copernicus)" },
  "natural-earth": { id: "natural-earth", name: "Natural Earth 1:110m cultural vectors", publisher: "Natural Earth", url: "https://www.naturalearthdata.com/", license: "public domain" },
  "usgs-wbd": { id: "usgs-wbd", name: "Watershed Boundary Dataset", publisher: "U.S. Geological Survey", url: "https://www.usgs.gov/national-hydrography/watershed-boundary-dataset", license: "public domain" },
  "epa-ecoregions": { id: "epa-ecoregions", name: "Level III and IV Ecoregions of the United States", publisher: "U.S. Environmental Protection Agency", url: "https://www.epa.gov/eco-research/ecoregions", license: "public domain" },
  "fema-nfhl": { id: "fema-nfhl", name: "National Flood Hazard Layer", publisher: "Federal Emergency Management Agency", url: "https://www.fema.gov/flood-maps/national-flood-hazard-layer", license: "public domain" },
  "nws-api": { id: "nws-api", name: "api.weather.gov points and zones", publisher: "NOAA National Weather Service", url: "https://www.weather.gov/documentation/services-web-api", license: "public domain" },
  "usgs-epqs": { id: "usgs-epqs", name: "Elevation Point Query Service (3DEP)", publisher: "U.S. Geological Survey", url: "https://apps.nationalmap.gov/epqs/", license: "public domain" },
  "nifc-wfigs": { id: "nifc-wfigs", name: "WFIGS Current Interagency Fire Perimeters and Wildland Fire Incident Locations", publisher: "National Interagency Fire Center", url: "https://data-nifc.opendata.arcgis.com/", license: "public; NIFC: not legal documents, no warranty" },
  "nasa-firms": { id: "nasa-firms", name: "FIRMS active fire data (VIIRS, MODIS NRT)", publisher: "NASA LANCE FIRMS, part of NASA ESDIS", url: "https://firms.modaps.eosdis.nasa.gov/", license: "NASA open data; acknowledgement requested" },
  gdacs: { id: "gdacs", name: "Global Disaster Alert and Coordination System", publisher: "European Commission Joint Research Centre", url: "https://www.gdacs.org/", license: "CC BY 4.0 (European Union), credit to GDACS" },
  "nasa-eonet": { id: "nasa-eonet", name: "Earth Observatory Natural Event Tracker (EONET) v3", publisher: "NASA", url: "https://eonet.gsfc.nasa.gov/", license: "NASA open data" },
  "usfws-nwi": { id: "usfws-nwi", name: "National Wetlands Inventory", publisher: "U.S. Fish and Wildlife Service", url: "https://www.fws.gov/program/national-wetlands-inventory", license: "public domain" },
  "usgs-padus": { id: "usgs-padus", name: "Protected Areas Database of the United States (PAD-US) 4.1", publisher: "U.S. Geological Survey Gap Analysis Project", url: "https://doi.org/10.5066/P96WBCHS", license: "public domain" },
  "gfz-kp": { id: "gfz-kp", name: "Geomagnetic Kp index", publisher: "GFZ Potsdam", url: "https://kp.gfz.de/", license: "CC BY 4.0" },
  "nasa-donki": { id: "nasa-donki", name: "Space Weather Database Of Notifications, Knowledge, Information (DONKI)", publisher: "NASA Community Coordinated Modeling Center", url: "https://kauai.ccmc.gsfc.nasa.gov/DONKI/", license: "NASA open data; experimental research information" },
  "youtube-oembed": { id: "youtube-oembed", name: "YouTube oEmbed (NASA's ISS live stream)", publisher: "YouTube", url: "https://www.youtube.com/@NASA", license: "YouTube Terms of Service; embedded player only" },
  // Zoning (lib/zoning). Licence strings are the dataset's own; where its metadata states none, the portal's terms apply and it says so.
  "seattle-zoning": { id: "seattle-zoning", name: "Current Land Use Zoning Detail", publisher: "City of Seattle, Office of Planning and Community Development, Department of Construction and Inspections", url: "https://www.arcgis.com/home/item.html?id=dd29065b5d01420e9686570c2b77502b", license: "PDDL (item licence); no warranty of accuracy" },
  "denver-zoning": { id: "denver-zoning", name: "Zoning (ODC_ZONE_ZONING_A)", publisher: "City and County of Denver", url: "https://www.arcgis.com/home/item.html?id=480d73ed76e041ba9f4faa05699c4f93", license: "provided as is, without warranty (Denver use constraints)" },
  "nyc-dcp-zoning": { id: "nyc-dcp-zoning", name: "Zoning Districts (NYZD) and MapPLUTO (tax lot at a point)", publisher: "NYC Department of City Planning", url: "https://www.nyc.gov/site/planning/data-maps/open-data.page", license: "no licence stated in the item metadata; MapPLUTO for informational purposes, no warranty" },
  "nyc-ztldb": { id: "nyc-ztldb", name: "Zoning Tax Lot Database (fdkv-4t4z)", publisher: "NYC Department of City Planning", url: "https://data.cityofnewyork.us/d/fdkv-4t4z", license: "no licence stated in the dataset metadata; NYC Open Data terms of use" },
  "chicago-zoning": { id: "chicago-zoning", name: "Boundaries - Zoning Districts (current) (dj47-wfun)", publisher: "City of Chicago", url: "https://data.cityofchicago.org/d/dj47-wfun", license: "City of Chicago data terms of use; the city's disclaimer is carried in caveats" },
  "dallas-zoning": { id: "dallas-zoning", name: "Base Zoning (f3t3-a5rd)", publisher: "City of Dallas", url: "https://www.dallasopendata.com/d/f3t3-a5rd", license: "no licence stated in the dataset metadata; Dallas OpenData terms" },
  "sanantonio-zoning": { id: "sanantonio-zoning", name: "CoSA Zoning (COSA_Zoning layer 12)", publisher: "City of San Antonio", url: "https://www.arcgis.com/home/item.html?id=5cdc1086f57541e892154eb8e6e86782", license: "provided as is, without warranty (City of San Antonio GIS disclaimer)" },
  "austin-zoning": { id: "austin-zoning", name: "Zoning (Small Map Scale)", publisher: "City of Austin, Geospatial Services - Data Development", url: "https://www.arcgis.com/home/item.html?id=c7f778d52d6145e99c7e36e61cf6998f", license: "for geographic reference, no warranty; acknowledgment of the City of Austin requested" },
  "la-zoning": { id: "la-zoning", name: "Generalized Zoning (City_Planning_Department MapServer layer 8)", publisher: "City of Los Angeles, Department of City Planning (LA GeoHub)", url: "https://maps.lacity.org/lahub/rest/services/City_Planning_Department/MapServer/8", license: "no licence stated on the service" },
  "sf-zoning": { id: "sf-zoning", name: "Zoning Districts (3i4a-hu95)", publisher: "San Francisco Planning Department", url: "https://data.sf.gov/d/3i4a-hu95", license: "Open Data Commons PDDL" },
  // Building permits, business licences, environmental permits (lib/permits).
  "chicago-permits": { id: "chicago-permits", name: "Building Permits (ydr8-5enu)", publisher: "City of Chicago", url: "https://data.cityofchicago.org/d/ydr8-5enu", license: "City of Chicago data terms of use; the city's disclaimer is carried in caveats" },
  "austin-permits": { id: "austin-permits", name: "Issued Construction Permits (3syk-w9eu)", publisher: "City of Austin, Texas - data.austintexas.gov", url: "https://data.austintexas.gov/d/3syk-w9eu", license: "Public Domain U.S. Government (dataset metadata)" },
  "seattle-permits": { id: "seattle-permits", name: "Building Permits (76t5-zqzr)", publisher: "City of Seattle, Department of Construction and Inspections", url: "https://data.seattle.gov/d/76t5-zqzr", license: "Public Domain (dataset metadata)" },
  "denver-permits": { id: "denver-permits", name: "Residential Construction Permits (ODC_DEV_RESIDENTIALCONSTPERMIT_P layer 316)", publisher: "City and County of Denver", url: "https://www.arcgis.com/home/item.html?id=014a873bf7444a658fc2ea0da7ad0704", license: "provided as is, without warranty (Denver use constraints)" },
  "nyc-dob-permits": { id: "nyc-dob-permits", name: "DOB NOW: Build - Approved Permits (rbx6-tga4)", publisher: "NYC Department of Buildings", url: "https://data.cityofnewyork.us/d/rbx6-tga4", license: "no licence stated in the dataset metadata; NYC Open Data terms of use" },
  "la-permits": { id: "la-permits", name: "Building Permits Issued from 2020 to Present (pi9x-tg5x)", publisher: "City of Los Angeles", url: "https://data.lacity.org/d/pi9x-tg5x", license: "no licence stated in the dataset metadata; Los Angeles Open Data terms" },
  "sf-permits": { id: "sf-permits", name: "Building Permits (i98e-djp9)", publisher: "City and County of San Francisco, Department of Building Inspection", url: "https://data.sf.gov/d/i98e-djp9", license: "Open Data Commons PDDL" },
  "ny-sla-licences": { id: "ny-sla-licences", name: "Liquor Authority Current List of Active Licenses (9s3h-dpkz)", publisher: "New York State Liquor Authority", url: "https://data.ny.gov/d/9s3h-dpkz", license: "no licence stated in the dataset metadata; Open NY terms of use" },
  "chicago-licences": { id: "chicago-licences", name: "Business Licenses (r5kz-chrr)", publisher: "City of Chicago", url: "https://data.cityofchicago.org/d/r5kz-chrr", license: "City of Chicago data terms of use; the city's disclaimer is carried in caveats" },
  "sf-business-locations": { id: "sf-business-locations", name: "Registered Business Locations (g8m3-pdis)", publisher: "City and County of San Francisco, Treasurer and Tax Collector", url: "https://data.sf.gov/d/g8m3-pdis", license: "Open Data Commons PDDL" },
  "la-active-businesses": { id: "la-active-businesses", name: "Listing of Active Businesses (6rrh-rzua)", publisher: "City of Los Angeles, Office of Finance", url: "https://data.lacity.org/d/6rrh-rzua", license: "CC0 1.0 Universal (Public Domain Dedication)" },
  "nyc-dcwp-licences": { id: "nyc-dcwp-licences", name: "Issued Licenses (w7w3-xahh), premises licences", publisher: "NYC Department of Consumer and Worker Protection", url: "https://data.cityofnewyork.us/d/w7w3-xahh", license: "no licence stated in the dataset metadata; NYC Open Data terms of use" },
  "epa-echo-cwa": { id: "epa-echo-cwa", name: "ECHO Clean Water Act (NPDES) facility search", publisher: "U.S. Environmental Protection Agency", url: "https://echo.epa.gov/tools/web-services", license: "public domain" },
  "epa-echo-air": { id: "epa-echo-air", name: "ECHO Clean Air Act facility search", publisher: "U.S. Environmental Protection Agency", url: "https://echo.epa.gov/tools/web-services", license: "public domain" },
  "usace-orm": { id: "usace-orm", name: "Regulatory Request System public permit search (ORM)", publisher: "U.S. Army Corps of Engineers", url: "https://permits.ops.usace.army.mil/orm-public", license: "public domain; undocumented public API, treated as unstable" },
  "federal-regions": { id: "federal-regions", name: "Federal regional office and Reserve district lists", publisher: "EPA, FEMA, Federal Reserve System", url: "https://www.federalreserve.gov/aboutthefed/federal-reserve-system.htm", license: "public domain" },
  "gev-snapshot": { id: "gev-snapshot", name: "Embedding Atlas feed snapshots", publisher: "Embedding Atlas", url: "https://github.com/jcdavis131/gods-eye-view", license: "MIT; derived counts of public feeds" },
} as const satisfies Record<string, SourceRef>;

export type SourceId = keyof typeof SOURCES;

export function source(id: SourceId): SourceRef {
  return SOURCES[id];
}
