// Registry of every public source the app relays. Add here first; refer by id
// everywhere else so a citation is always spelled the same way.
import type { SourceRef } from "./types";

export const SOURCES = {
  "bls-oews": { id: "bls-oews", name: "Occupational Employment and Wage Statistics", publisher: "U.S. Bureau of Labor Statistics", url: "https://www.bls.gov/oes/", license: "public domain" },
  "bls-qcew": { id: "bls-qcew", name: "Quarterly Census of Employment and Wages", publisher: "U.S. Bureau of Labor Statistics", url: "https://www.bls.gov/cew/", license: "public domain" },
  "zillow-zhvi": { id: "zillow-zhvi", name: "Zillow Home Value Index (ZHVI)", publisher: "Zillow Research", url: "https://www.zillow.com/research/data/", license: "free for public use with attribution" },
  "zillow-zori": { id: "zillow-zori", name: "Zillow Observed Rent Index (ZORI)", publisher: "Zillow Research", url: "https://www.zillow.com/research/data/", license: "free for public use with attribution" },
  fred: { id: "fred", name: "FRED Economic Data", publisher: "Federal Reserve Bank of St. Louis", url: "https://fred.stlouisfed.org/", license: "FRED terms; series from their original publishers" },
  "bts-border": { id: "bts-border", name: "Border Crossing Entry Data", publisher: "U.S. Bureau of Transportation Statistics", url: "https://data.bts.gov/", license: "public domain" },
  "bts-ports": { id: "bts-ports", name: "Port Performance Freight Statistics", publisher: "U.S. Bureau of Transportation Statistics", url: "https://data.bts.gov/", license: "public domain" },
  "bts-supply-chain": { id: "bts-supply-chain", name: "Supply Chain and Freight Indicators", publisher: "U.S. Bureau of Transportation Statistics", url: "https://data.bts.gov/", license: "public domain" },
  "nga-wpi": { id: "nga-wpi", name: "World Port Index (Pub 150)", publisher: "National Geospatial-Intelligence Agency", url: "https://msi.nga.mil/Publications/WPI", license: "public domain" },
  "worldbank-wdi": { id: "worldbank-wdi", name: "World Development Indicators", publisher: "World Bank", url: "https://data.worldbank.org/", license: "CC BY 4.0" },
  "worldbank-wits": { id: "worldbank-wits", name: "WITS TradeStats", publisher: "World Bank", url: "https://wits.worldbank.org/", license: "CC BY 4.0" },
  "census-tigerweb": { id: "census-tigerweb", name: "TIGERweb", publisher: "U.S. Census Bureau", url: "https://tigerweb.geo.census.gov/", license: "public domain" },
  "usgs-water": { id: "usgs-water", name: "USGS Water Data API", publisher: "U.S. Geological Survey", url: "https://api.waterdata.usgs.gov/", license: "public domain" },
  "usgs-stat": { id: "usgs-stat", name: "USGS Water Data Statistics API (daily streamflow percentiles)", publisher: "U.S. Geological Survey", url: "https://api.waterdata.usgs.gov/statistics/v0/", license: "public domain" },
  "noaa-nwps": { id: "noaa-nwps", name: "National Water Prediction Service", publisher: "NOAA National Weather Service", url: "https://api.water.noaa.gov/", license: "public domain" },
  twdb: { id: "twdb", name: "Water Data for Texas reservoirs", publisher: "Texas Water Development Board", url: "https://www.waterdatafortexas.org/reservoirs", license: "public" },
  usdm: { id: "usdm", name: "U.S. Drought Monitor", publisher: "National Drought Mitigation Center, USDA, NOAA", url: "https://droughtmonitor.unl.edu/", license: "public with attribution" },
  "usgs-earthquakes": { id: "usgs-earthquakes", name: "Earthquake Hazards Program feeds", publisher: "U.S. Geological Survey", url: "https://earthquake.usgs.gov/", license: "public domain" },
  "adsb-lol": { id: "adsb-lol", name: "adsb.lol ADS-B feed", publisher: "adsb.lol", url: "https://adsb.lol/", license: "ODbL" },
  opensky: { id: "opensky", name: "OpenSky Network", publisher: "OpenSky Network", url: "https://opensky-network.org/", license: "OpenSky terms (non-commercial)" },
  digitraffic: { id: "digitraffic", name: "Marine traffic AIS", publisher: "Fintraffic / Digitraffic", url: "https://www.digitraffic.fi/en/marine-traffic/", license: "CC BY 4.0" },
  aisstream: { id: "aisstream", name: "AISStream", publisher: "AISStream.io", url: "https://aisstream.io/", license: "free key; AISStream terms" },
  celestrak: { id: "celestrak", name: "GP element sets", publisher: "CelesTrak", url: "https://celestrak.org/", license: "CelesTrak terms" },
  "sec-edgar": { id: "sec-edgar", name: "EDGAR company filings and XBRL APIs", publisher: "U.S. Securities and Exchange Commission", url: "https://www.sec.gov/search-filings/edgar-application-programming-interfaces", license: "public domain; fair-access policy (10 req/s, User-Agent)" },
  "fdic-bankfind": { id: "fdic-bankfind", name: "BankFind Suite API", publisher: "Federal Deposit Insurance Corporation", url: "https://banks.data.fdic.gov/docs/", license: "public domain" },
  usaspending: { id: "usaspending", name: "USAspending API", publisher: "U.S. Department of the Treasury", url: "https://api.usaspending.gov/", license: "public domain" },
  "census-zcta-county": { id: "census-zcta-county", name: "ZCTA to county relationship file (2020)", publisher: "U.S. Census Bureau", url: "https://www.census.gov/geographies/reference-files/time-series/geo/relationship-files.html", license: "public domain" },
  "sentinel-2": { id: "sentinel-2", name: "Copernicus Sentinel-2 L2A", publisher: "ESA via Element 84 Earth Search", url: "https://earth-search.aws.element84.com/v1", license: "free and open (Copernicus)" },
  "natural-earth": { id: "natural-earth", name: "Natural Earth 1:110m cultural vectors", publisher: "Natural Earth", url: "https://www.naturalearthdata.com/", license: "public domain" },
  "usgs-wbd": { id: "usgs-wbd", name: "Watershed Boundary Dataset", publisher: "U.S. Geological Survey", url: "https://www.usgs.gov/national-hydrography/watershed-boundary-dataset", license: "public domain" },
  "epa-ecoregions": { id: "epa-ecoregions", name: "Level III and IV Ecoregions of the United States", publisher: "U.S. Environmental Protection Agency", url: "https://www.epa.gov/eco-research/ecoregions", license: "public domain" },
  "fema-nfhl": { id: "fema-nfhl", name: "National Flood Hazard Layer", publisher: "Federal Emergency Management Agency", url: "https://www.fema.gov/flood-maps/national-flood-hazard-layer", license: "public domain" },
  "nws-api": { id: "nws-api", name: "api.weather.gov points and zones", publisher: "NOAA National Weather Service", url: "https://www.weather.gov/documentation/services-web-api", license: "public domain" },
  "usgs-epqs": { id: "usgs-epqs", name: "Elevation Point Query Service (3DEP)", publisher: "U.S. Geological Survey", url: "https://apps.nationalmap.gov/epqs/", license: "public domain" },
  "nifc-wfigs": { id: "nifc-wfigs", name: "WFIGS Current Interagency Fire Perimeters and Wildland Fire Incident Locations", publisher: "National Interagency Fire Center", url: "https://data-nifc.opendata.arcgis.com/", license: "public; NIFC: not legal documents, no warranty" },
  "nasa-firms": { id: "nasa-firms", name: "FIRMS active fire data (VIIRS, MODIS NRT)", publisher: "NASA LANCE FIRMS, part of NASA ESDIS", url: "https://firms.modaps.eosdis.nasa.gov/", license: "NASA open data; acknowledgement requested" },
  gdacs: { id: "gdacs", name: "Global Disaster Alert and Coordination System", publisher: "European Commission Joint Research Centre", url: "https://www.gdacs.org/", license: "CC BY 4.0 (European Union), credit to GDACS" },
  "nasa-eonet": { id: "nasa-eonet", name: "Earth Observatory Natural Event Tracker (EONET) v3", publisher: "NASA", url: "https://eonet.gsfc.nasa.gov/", license: "NASA open data" },
  "usfws-nwi": { id: "usfws-nwi", name: "National Wetlands Inventory", publisher: "U.S. Fish and Wildlife Service", url: "https://www.fws.gov/program/national-wetlands-inventory", license: "public domain" },
  "usgs-padus": { id: "usgs-padus", name: "Protected Areas Database of the United States (PAD-US) 4.1", publisher: "U.S. Geological Survey Gap Analysis Project", url: "https://doi.org/10.5066/P96WBCHS", license: "public domain" },
  "gfz-kp": { id: "gfz-kp", name: "Geomagnetic Kp index", publisher: "GFZ Potsdam", url: "https://kp.gfz.de/", license: "CC BY 4.0" },
  "nasa-donki": { id: "nasa-donki", name: "Space Weather Database Of Notifications, Knowledge, Information (DONKI)", publisher: "NASA Community Coordinated Modeling Center", url: "https://kauai.ccmc.gsfc.nasa.gov/DONKI/", license: "NASA open data; experimental research information" },
  "youtube-oembed": { id: "youtube-oembed", name: "YouTube oEmbed (NASA's ISS live stream)", publisher: "YouTube", url: "https://www.youtube.com/@NASA", license: "YouTube Terms of Service; embedded player only" },
  // Parcels & ownership (/api/parcels): each county or state service as its publisher names it.
  "txgio-stratmap": { id: "txgio-stratmap", name: "StratMap Land Parcels (most recent)", publisher: "Texas Geographic Information Office (TxGIO), from each county appraisal district", url: "https://feature.geographic.texas.gov/arcgis/rest/services/Parcels/stratmap_land_parcels_48_most_recent/MapServer", license: "Texas public records; attribute TxGIO and the appraisal district" },
  "hcad-parcels": { id: "hcad-parcels", name: "HCAD Parcels", publisher: "Harris Central Appraisal District", url: "https://www.gis.hctx.net/arcgis/rest/services/HCAD/Parcels/MapServer", license: "county public record" },
  "tcad-parcels": { id: "tcad-parcels", name: "TCAD public parcels", publisher: "Travis County, from the Travis Central Appraisal District", url: "https://gis.traviscountytx.gov/server1/rest/services/Boundaries_and_Jurisdictions/TCAD_public/MapServer", license: "county public record" },
  "maricopa-assessor": { id: "maricopa-assessor", name: "Maricopa County Assessor parcels (MaricopaDynamicQueryService)", publisher: "Maricopa County Assessor's Office", url: "https://mcassessor.maricopa.gov/", license: "public record; Assessor's disclaimer" },
  "lacounty-assessor": { id: "lacounty-assessor", name: "LA County Parcels", publisher: "Los Angeles County Office of the Assessor", url: "https://portal.assessor.lacounty.gov/", license: "LA County open data" },
  "cook-parcels": { id: "cook-parcels", name: "CookViewer3Parcels and Assessor - Parcel Addresses (3723-97qp)", publisher: "Cook County GIS and Cook County Assessor's Office", url: "https://datacatalog.cookcountyil.gov/d/3723-97qp", license: "Cook County open data terms" },
  "king-parcels": { id: "king-parcels", name: "KingCo_PropertyInfo parcels", publisher: "King County GIS Center and Department of Assessments", url: "https://gismaps.kingcounty.gov/arcgis/rest/services/Property/KingCo_PropertyInfo/MapServer", license: "public; King County disclaimer" },
  "detroit-parcels": { id: "detroit-parcels", name: "Parcels (current)", publisher: "City of Detroit", url: "https://services2.arcgis.com/qvkbeam7Wirps6zC/arcgis/rest/services/parcel_file_current/FeatureServer", license: "City of Detroit open data" },
  "wi-parcels": { id: "wi-parcels", name: "Wisconsin Statewide Parcel Map (V12)", publisher: "Wisconsin State Cartographer's Office and Department of Administration", url: "https://services3.arcgis.com/n6uYoouQZW75n5WI/arcgis/rest/services/Wisconsin_Statewide_Parcels_DB/FeatureServer", license: "free for public consumption" },
  "nc-parcels": { id: "nc-parcels", name: "NC1Map Parcels", publisher: "NC Center for Geographic Information and Analysis (NC OneMap)", url: "https://services.nconemap.gov/secure/rest/services/NC1Map_Parcels/FeatureServer", license: "public; CGIA disclaimer" },
  "mt-cadastral": { id: "mt-cadastral", name: "Montana Cadastral Framework", publisher: "Montana State Library and Department of Revenue", url: "https://gisservice.mt.gov/arcgis/rest/services/msdi_cadastral_map_v1/MapServer", license: "public" },
  "mn-parcels": { id: "mn-parcels", name: "Minnesota Parcels, Open Data", publisher: "Minnesota Geospatial Information Office (MnGeo), from counties that opt in", url: "https://enterprise.gisdata.mn.gov/aghost/rest/services/us_mn_state_mngeo/plan_parcels_open/FeatureServer", license: "open data; opted-in counties" },
  "fl-dor-cadastral": { id: "fl-dor-cadastral", name: "Florida Statewide Cadastral", publisher: "Florida Department of Revenue, from the county property appraisers", url: "https://services9.arcgis.com/Gh9awoU677aKree0/arcgis/rest/services/Florida_Statewide_Cadastral/FeatureServer", license: "public record; DOR disclaimer" },
  "massgis-parcels": { id: "massgis-parcels", name: "Massachusetts Property Tax Parcels", publisher: "MassGIS (Bureau of Geographic Information)", url: "https://services1.arcgis.com/hGdibHYSPO59RG1h/arcgis/rest/services/Massachusetts_Property_Tax_Parcels/FeatureServer", license: "public; not authoritative boundaries" },
  "vcgi-parcels": { id: "vcgi-parcels", name: "Vermont standardized parcels with Grand List", publisher: "Vermont Center for Geographic Information", url: "https://services1.arcgis.com/BkFxaEFNwHqX3tAw/ArcGIS/rest/services/FS_VCGI_VTPARCELS_WM_NOCACHE_v2/FeatureServer", license: "public; no warranty" },
  "ugrc-lir": { id: "ugrc-lir", name: "Utah LIR parcels (one service per county)", publisher: "Utah Geospatial Resource Center, from each county assessor", url: "https://services1.arcgis.com/99lidPhWCzftIe9K/arcgis/rest/services", license: "public; as is" },
  "ohio-parcels": { id: "ohio-parcels", name: "Ohio Statewide Parcels Public View", publisher: "Ohio Geographically Referenced Information Program (OGRIP), from each county auditor", url: "https://services2.arcgis.com/MlJ0G8iWUyC7jAmu/arcgis/rest/services/OhioStatewidePacels_full_view/FeatureServer", license: "public use at the user's own risk" },
  "njogis-parcels": { id: "njogis-parcels", name: "Parcels and MOD-IV Composite", publisher: "NJ Office of GIS (NJOGIS)", url: "https://maps.nj.gov/arcgis/rest/services/Framework/Cadastral/MapServer", license: "public; owner names redacted under Daniel's Law" },
  "nys-tax-parcels": { id: "nys-tax-parcels", name: "NYS Tax Parcels Public", publisher: "NYS Office of Information Technology Services and Department of Taxation, from contributing counties", url: "https://gisservices.its.ny.gov/arcgis/rest/services/NYS_Tax_Parcels_Public/FeatureServer", license: "public; counties authorised sharing" },
  "ct-parcels": { id: "ct-parcels", name: "Connecticut CAMA and Parcel Layer 2025", publisher: "State of Connecticut Office of Policy and Management", url: "https://services3.arcgis.com/3FL1kr7L4LvwA2Kb/arcgis/rest/services/Connecticut_CAMA_and_Parcel_Layer_2025/FeatureServer", license: "CC0" },
  "md-parcels": { id: "md-parcels", name: "MD Parcel Boundaries with SDAT data", publisher: "MD iMAP, Maryland Department of Planning and SDAT", url: "https://mdgeodata.md.gov/imap/rest/services/PlanningCadastre/MD_ParcelBoundaries/MapServer", license: "public" },
  "usdot-nad": { id: "usdot-nad", name: "National Address Database address points", publisher: "U.S. Department of Transportation", url: "https://services.arcgis.com/xOi1kZaI0eWDREZv/ArcGIS/rest/services/Address_Points_from_National_Address_Database_view/FeatureServer", license: "public domain; not for use as a mailing list" },
  "blm-plss": { id: "blm-plss", name: "National PLSS CadNSDI (townships and sections)", publisher: "Bureau of Land Management", url: "https://gis.blm.gov/arcgis/rest/services/Cadastral/BLM_Natl_PLSS_CadNSDI/MapServer", license: "public domain" },
  "federal-regions": { id: "federal-regions", name: "Federal regional office and Reserve district lists", publisher: "EPA, FEMA, Federal Reserve System", url: "https://www.federalreserve.gov/aboutthefed/federal-reserve-system.htm", license: "public domain" },
  "gev-snapshot": { id: "gev-snapshot", name: "Embedding Atlas feed snapshots", publisher: "Embedding Atlas", url: "https://github.com/jcdavis131/gods-eye-view", license: "MIT; derived counts of public feeds" },
} as const satisfies Record<string, SourceRef>;

export type SourceId = keyof typeof SOURCES;

export function source(id: SourceId): SourceRef {
  return SOURCES[id];
}
